const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    colors: {
      first: '#1DB954',
      second: '#212121',
      third: '#535353',
      fourth: '#B3B3B3',
      dark: '#121212',
      contrast: '#ffffff',
      error: '#c62828',
      ...defaultTheme.colors,
    },
    extend: {
      fontFamily: {
        'title-100': ['Poppins-Thin'],
        'title-100-italic': ['Poppins-ThinItalic'],
        'title-200': ['Poppins-ExtraLight'],
        'title-200-italic': ['Poppins-ExtraLightItalic'],
        'title-300': ['Poppins-Light'],
        'title-300-italic': ['Poppins-LightItalic'],
        'title-400': ['Poppins-Regular'],
        'title-400-italic': ['Poppins-italic'],
        'title-500': ['Poppins-Medium'],
        'title-500-italic': ['Poppins-MediumItalic'],
        'title-600': ['Poppins-SemiBold'],
        'title-600-italic': ['Poppins-SemiBoldItalic'],
        'title-700': ['Poppins-Bold'],
        'title-700-italic': ['Poppins-BoldItalic'],
        'title-800': ['Poppins-ExtraBold'],
        'title-800-italic': ['Poppins-ExtraBoldItalic'],
        'title-900': ['Poppins-Black'],
        'title-900-italic': ['Poppins-BlackItalic'],

        'body-100': ['WorkSans-Thin'],
        'body-100-italic': ['WorkSans-ThinItalic'],
        'body-200': ['WorkSans-ExtraLight'],
        'body-200-italic': ['WorkSans-ExtraLightItalic'],
        'body-300': ['WorkSans-Light'],
        'body-300-italic': ['WorkSans-LightItalic'],
        'body-400': ['WorkSans-Regular'],
        'body-400-italic': ['WorkSans-italic'],
        'body-500': ['WorkSans-Medium'],
        'body-500-italic': ['WorkSans-MediumItalic'],
        'body-600': ['WorkSans-SemiBold'],
        'body-600-italic': ['WorkSans-SemiBoldItalic'],
        'body-700': ['WorkSans-Bold'],
        'body-700-italic': ['WorkSans-BoldItalic'],
        'body-800': ['WorkSans-ExtraBold'],
        'body-800-italic': ['WorkSans-ExtraBoldItalic'],
        'body-900': ['WorkSans-Black'],
        'body-900-italic': ['WorkSans-BlackItalic'],
      },
    },
  },
  plugins: [],
};
