import { AppThemes } from './types.config';

const theme: AppThemes = {
  light: {
    base: '#F9F9FB',
    baseHighlight: '#ffffff',
    baseContrast: '#4B4E6D',
    baseContrastBold: '#272C56',
    primary: '#3786EB',
    primaryFocus: '#5F9EEF',
    primaryContrast: '#ffffff',
    secondary: '#F3747F',
    secondaryFocus: '#F58A93',
    secondaryContrast: '#ffffff',
    third: '#F9AA4B',
    thirdFocus: '#FBBB60',
    thirdContrast: '#ffffff',
    fourth: '#18B797',
    fourthFocus: '#2BC0A4',
    fourthContrast: '#ffffff',
    neutral: '#95a5a6',
    neutralFocus: '#A6B6B7',
    neutralContrast: '#ffffff',
    error: '#e74c3c',
    errorFocus: '#EB6A60',
    errorContrast: '#ffffff',
  },
  dark: {
    base: '#272C56',
    baseHighlight: '#4B4E6D',
    baseContrast: '#F9F9FB',
    baseContrastBold: '#ffffff',
    primary: '#5F9EEF',
    primaryFocus: '#3786EB',
    primaryContrast: '#272C56',
    secondary: '#F58A93',
    secondaryFocus: '#F3747F',
    secondaryContrast: '#272C56',
    third: '#FBBB60',
    thirdFocus: '#F9AA4B',
    thirdContrast: '#272C56',
    fourth: '#2BC0A4',
    fourthFocus: '#18B797',
    fourthContrast: '#272C56',
    neutral: '#A6B6B7',
    neutralFocus: '#95a5a6',
    neutralContrast: '#272C56',
    error: '#EB6A60',
    errorFocus: '#e74c3c',
    errorContrast: '#272C56',
  },
};

export default theme;
